import { CardData } from '../modules/components/card/card';

const Data: CardData[] = [
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Bornheim-No.-3.jpg',
    name: 'Bornheim No. 3',
    price: '146$',
    ammo: '5+1/10',
    damage: '74',
    distance: '64m',
    reload: '3s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Bornheim-No3-Extended.jpg',
    name: 'Bornheim No. 3 Extended',
    price: '203$',
    ammo: '8+1/10',
    damage: '74',
    distance: '64m',
    reload: '8s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/10/Bornheim-No3-Match.jpg',
    name: 'Bornheim No. 3 Match',
    price: '180$',
    ammo: '5+1/10',
    damage: '80',
    distance: '68m',
    reload: '3s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Caldwell-Conversion-Pistol.jpg',
    name: 'Caldwell Conversion Pistol',
    price: '55$',
    ammo: '6/18',
    damage: '104',
    distance: '84m',
    reload: '11s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Caldwell-Conversion-Chain-Pistol.jpg',
    name: 'Caldwell Conversion Chain Pistol',
    price: '84$',
    ammo: '17/18',
    damage: '104',
    distance: '84m',
    reload: '28s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Caldwell-Conversion-Uppercut.jpg',
    name: 'Caldwell Conversion Uppercut',
    price: '414$',
    ammo: '6/9',
    damage: '126',
    distance: '115m',
    reload: '15s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Caldwell-Pax.jpg',
    name: 'Caldwell Pax',
    price: '80$',
    ammo: '6/12',
    damage: '110',
    distance: '86m',
    reload: '11s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Dolch-96.jpg',
    name: 'Dolch 96',
    price: '750$',
    ammo: '10/10',
    damage: '97',
    distance: '78m',
    reload: '6s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Dolch-96-Precision.jpg',
    name: 'Dolch 96 Precision',
    price: '790$',
    ammo: '10/10',
    damage: '97',
    distance: '78m',
    reload: '6s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/LeMat-Mark-II.jpg',
    name: 'LeMat Mark II',
    price: '95$',
    ammo: '9/18',
    damage: '97',
    distance: '79m',
    reload: '15s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895.jpg',
    name: 'Nagant M1895',
    price: '24$',
    ammo: '7/21',
    damage: '91',
    distance: '73m',
    reload: '12s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895-Deadeye.jpg',
    name: 'Nagant M1895 Deadeye',
    price: '42$',
    ammo: '7/21',
    damage: '91',
    distance: '73m',
    reload: '13s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895-Officer.jpg',
    name: 'Nagant M1895 Officer',
    price: '96$',
    ammo: '7/14',
    damage: '91',
    distance: '73m',
    reload: '12s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895-Officer-Carbine.jpg',
    name: 'Nagant M1895 Officer Carbine',
    price: '155$',
    ammo: '7/14',
    damage: '104',
    distance: '125m',
    reload: '12s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2020/12/Nagant-M1895-Officer-Carbine-Deadeye_small.jpg',
    name: 'Nagant M1895 Officer Carbine Deadeye',
    price: '211$',
    ammo: '7/14',
    damage: '104',
    distance: '125m',
    reload: '12s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895-Precision.jpg',
    name: 'Nagant M1895 Precision',
    price: '29$',
    ammo: '7/21',
    damage: '91',
    distance: '73m',
    reload: '13s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Nagant-M1895-Silencer.jpg',
    name: 'Nagant M1895 Silencer',
    price: '93$',
    ammo: '7/21',
    damage: '91',
    distance: '56m',
    reload: '12s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2019/08/Quad-Derringer.jpg',
    name: 'Quad Derringer',
    price: '30$',
    ammo: '4/12',
    damage: '74',
    distance: '60m',
    reload: '3s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2021/10/Scottfield-Model-N3-small.jpg',
    name: 'Scottfield Model 3',
    price: '77$',
    ammo: '6/12',
    damage: '107',
    distance: '85m',
    reload: '9s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2022/01/Scottfield-Model-3-Precision_small.jpg',
    name: 'Scottfield Model 3 Precision',
    price: '85$',
    ammo: '6/12',
    damage: '107',
    distance: '85m',
    reload: '9s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2022/01/Scottfield-Model-3-Spitfire_small.jpg',
    name: 'Scottfield Model 3 Spitfire',
    price: '108$',
    ammo: '6/12',
    damage: '107',
    distance: '85m',
    reload: '9s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2022/01/Scottfield-Model-3-Swift_small.jpg',
    name: 'Scottfield Model 3 Swift',
    price: '95$',
    ammo: '6/12',
    damage: '107',
    distance: '85m',
    reload: '4s',
  },
  {
    img: 'https://huntzone.varshevsky.com/wp-content/uploads/2022/12/Sparks-Pistol_small.jpg',
    name: 'Sparks Pistol',
    price: '155$',
    ammo: '1/14',
    damage: '149',
    distance: '150m',
    reload: '4s',
  },
];

export default Data;
